@startuml
start
:Read <b>Commandline</b>;
if(is <b>ExecutableQueryResult</b>) is (yes) then
    :Replace alias params with user params;
else (no)    
endif
if(alias is null) is (yes) then
    :Display warning;
else (no)
    if(alias is <b>IExecutable</b>) is (yes) then
        :Execute alias;
        note right
        The <b>IExecutable</b> already 
        contains the behaviour for 
        execution.This has been set 
        when the user made a search
        with <b>SearchService</b>.
        end note
    else (no)
        :Display warning;
    endif
endif
stop
@end