
title: Lanceur 
description: >- 
  Lanceur : Launch anything, instantly.
theme: just-the-docs
favicon_ico: "/assets/favicon.ico"

permalink: /:title:output_ext
aux_links:
  Lanceur on GitHub: https://github.com/jibedoubleve/lanceur-bis

color_scheme: dark

callouts:
  information:
    title: Information
    color: yellow
  note:
    title: Note
    color: blue