title: Lanceur
description: >-
  Lanceur : Launch anything, instantly.
theme: just-the-docs
favicon_ico: "/assets/favicon.ico"

repository: jibedoubleve/lanceur-bis
url: 'https://jibedoubleve.github.io' 
baseurl: '/lanceur-bis'

plugins:
  - "jekyll-github-metadata"

aux_links:
  Lanceur on GitHub: https://github.com/jibedoubleve/lanceur-bis

nav_external_links:
  - title: Releases download page
    url: https://github.com/jibedoubleve/lanceur-bis/releases
    hide_icon: false
    opens_in_new_tab: true


color_scheme: dark

callouts:
  information:
    title: Information
    color: yellow
  note:
    title: Note
    color: blue
