
title: Lanceur
description: >- 
  Lanceur : Launch anything, instantly.
github_username:  jibedoubleve
theme: just-the-docs

url: https://jibedoubleve.github.io/gitsandbox/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# ---------------------------
# - Configure Minima theme  -
# ---------------------------

favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/logo.png"
