# When a pull request is merged (therefor a push), 
# execute tests and release the packages in GitHub
name: Release
on:
  push:
    branches: 
      - master
      - 'release/**'
jobs:
  build:
    name: Release
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v1

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore dotnet tools
        run: dotnet tool restore
        
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        env: 
          CAKE_PUBLIC_GITHUB_TOKEN: ${{secrets.CAKE_PUBLIC_GITHUB_TOKEN}}
          CAKE_PUBLIC_GITHUB_USERNAME: ${{secrets.CAKE_PUBLIC_GITHUB_USERNAME}}
        with:
          target: github
